import type { LucideIcon } from "lucide-react";
import {
  Archive,
  BarChart3,
  BookOpen,
  Box,
  Calendar,
  CalendarClock,
  CalendarDays,
  ClipboardList,
  Clock,
  Cloud,
  Coins,
  Dices,
  DoorOpen,
  Dumbbell,
  Eye,
  FolderKanban,
  GraduationCap,
  Hammer,
  Handshake,
  Image,
  Info,
  Languages,
  LayoutDashboard,
  LayoutList,
  Layers,
  Lightbulb,
  LineChart,
  ListOrdered,
  Map,
  Megaphone,
  MessageSquare,
  Paintbrush,
  Palette,
  PanelsTopLeft,
  Pause,
  Pencil,
  PenTool,
  Play,
  Presentation,
  Printer,
  Puzzle,
  Radio,
  RotateCcw,
  Sparkles,
  Star,
  Store,
  Sun,
  Target,
  Timer,
  Trophy,
  Users,
  Vote,
  Wrench,
} from "lucide-react";

/** One pictogram per place. Word stays next to it. */
export const NAV_MARK: Record<string, LucideIcon> = {
  dash: LayoutDashboard,
  wall: PanelsTopLeft,
  overview: PanelsTopLeft,
  teach: Presentation,
  deck: Layers,
  week: CalendarDays,
  year: Trophy,
  polls: Vote,
  data: BarChart3,
  club: Star,
  clubwall: Star,
  hall: DoorOpen,
  hallwall: DoorOpen,
  studyhall: DoorOpen,
  learn: BookOpen,
  book: GraduationCap,
  grades: GraduationCap,
  projects: FolderKanban,
  skills: Hammer,
  words: Languages,
  guide: Map,
  crew: Users,
  score: Users,
  people: Users,
  crews: Users,
  roster: ClipboardList,
  records: Archive,
  vault: Archive,
  cloud: Cloud,
  admin: Wrench,
  today: Sun,
  day: Clock,
  class: Target,
  economy: Coins,
  modules: Puzzle,
  look: Palette,
  room: Palette,
  about: Info,
  stocks: LineChart,
  wallet: LineChart,
  lucky: Dices,
  store: Store,
  prints: Printer,
  now: Clock,
  proc: ListOrdered,
  strip: CalendarClock,
  specials: Megaphone,
  mods: Puzzle,
  tools: Timer,
  notes: Megaphone,
  kpis: Trophy,
  poll: Vote,
  xp: Trophy,
  perk: Coins,
  rank: Trophy,
  all: LayoutList,
  live: Radio,
  q1: Calendar,
  q2: Calendar,
  q3: Calendar,
  q4: Calendar,
  hold: Pause,
  legal: Eye,
  schooltool: ClipboardList,
  reset: RotateCcw,
  top: Trophy,
  gallery: Image,
  buy: Handshake,
  desk: Handshake,
  stock: Archive,
  bin: Archive,
};

export const STAGE_MARK: Record<string, LucideIcon> = {
  "IDEA STAGE": Lightbulb,
  "DESIGN STAGE": PenTool,
  "MODELING STAGE": Box,
  "FINISHING STAGE": Paintbrush,
  "PRESENTATION PREP": Presentation,
  "CRITIQUE DAY": MessageSquare,
  TRAINING: Dumbbell,
  DEMONSTRATION: Play,
  DRAWING: Pencil,
  "FREE DAY": Sparkles,
  PRODUCTIVITY: Timer,
};

export function markOf(id: string): LucideIcon | undefined {
  return NAV_MARK[id] ?? STAGE_MARK[id];
}
